//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuShoppingCart_Angular.ShoppingCartServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="shoppingCartDataContract.itemDetailsDataContract", Namespace="http://schemas.datacontract.org/2004/07/ShanuSchoppingCart_WCF")]
    [System.SerializableAttribute()]
    public partial class shoppingCartDataContractitemDetailsDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddedBy {
            get {
                return this.AddedByField;
            }
            set {
                if ((object.ReferenceEquals(this.AddedByField, value) != true)) {
                    this.AddedByField = value;
                    this.RaisePropertyChanged("AddedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Name {
            get {
                return this.Image_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_NameField, value) != true)) {
                    this.Image_NameField = value;
                    this.RaisePropertyChanged("Image_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Date {
            get {
                return this.Item_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_DateField, value) != true)) {
                    this.Item_DateField = value;
                    this.RaisePropertyChanged("Item_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_ID {
            get {
                return this.Item_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_IDField, value) != true)) {
                    this.Item_IDField = value;
                    this.RaisePropertyChanged("Item_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Name {
            get {
                return this.Item_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_NameField, value) != true)) {
                    this.Item_NameField = value;
                    this.RaisePropertyChanged("Item_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Price {
            get {
                return this.Item_PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_PriceField, value) != true)) {
                    this.Item_PriceField = value;
                    this.RaisePropertyChanged("Item_Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingCartServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemDetails", ReplyAction="http://tempuri.org/IService1/GetItemDetailsResponse")]
        shanuShoppingCart_Angular.ShoppingCartServiceReference.shoppingCartDataContractitemDetailsDataContract[] GetItemDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItemDetails", ReplyAction="http://tempuri.org/IService1/GetItemDetailsResponse")]
        System.Threading.Tasks.Task<shanuShoppingCart_Angular.ShoppingCartServiceReference.shoppingCartDataContractitemDetailsDataContract[]> GetItemDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : shanuShoppingCart_Angular.ShoppingCartServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<shanuShoppingCart_Angular.ShoppingCartServiceReference.IService1>, shanuShoppingCart_Angular.ShoppingCartServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public shanuShoppingCart_Angular.ShoppingCartServiceReference.shoppingCartDataContractitemDetailsDataContract[] GetItemDetails() {
            return base.Channel.GetItemDetails();
        }
        
        public System.Threading.Tasks.Task<shanuShoppingCart_Angular.ShoppingCartServiceReference.shoppingCartDataContractitemDetailsDataContract[]> GetItemDetailsAsync() {
            return base.Channel.GetItemDetailsAsync();
        }
    }
}
