

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Scenario2.xaml.h"




void ::SDKSample::PlayTo::Scenario2::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Scenario2.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario2.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'Input'
    Input = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Input"));
    // Get the Grid named 'Output'
    Output = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Output"));
    // Get the ListBox named 'Playlist'
    Playlist = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Playlist"));
    // Get the Image named 'ImageSource'
    ImageSource = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageSource"));
    // Get the ListBoxItem named 'Item1'
    Item1 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Item1"));
    // Get the ListBoxItem named 'Item2'
    Item2 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Item2"));
    // Get the ListBoxItem named 'Item3'
    Item3 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Item3"));
    // Get the ListBoxItem named 'Item4'
    Item4 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Item4"));
    // Get the ListBoxItem named 'Item5'
    Item5 = safe_cast<::Windows::UI::Xaml::Controls::ListBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Item5"));
    // Get the TextBlock named 'InputTextBlock1'
    InputTextBlock1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"InputTextBlock1"));
    // Get the Button named 'playSlideshow'
    playSlideshow = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playSlideshow"));
    // Get the Button named 'pauseSlideshow'
    pauseSlideshow = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pauseSlideshow"));
    // Get the Button named 'previousItem'
    previousItem = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"previousItem"));
    // Get the Button named 'nextItem'
    nextItem = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"nextItem"));
    // Get the VisualState named 'DefaultLayout'
    DefaultLayout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DefaultLayout"));
    // Get the VisualState named 'Below768Layout'
    Below768Layout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Below768Layout"));
}

void ::SDKSample::PlayTo::Scenario2::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SDKSample::PlayTo::Scenario2::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&Scenario2::Playlist_SelectionChanged);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::PlayTo::Scenario2::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&Scenario2::playSlideshow_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::PlayTo::Scenario2::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&Scenario2::pauseSlideshow_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::PlayTo::Scenario2::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&Scenario2::previousItem_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::PlayTo::Scenario2::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&Scenario2::nextItem_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

