

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ListBox;
                ref class Image;
                ref class ListBoxItem;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKSample
{
    namespace PlayTo
    {
        partial ref class Scenario2 : public ::SDKSample::Common::LayoutAwarePage, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
            private: ::Windows::UI::Xaml::Controls::Grid^ Input;
            private: ::Windows::UI::Xaml::Controls::Grid^ Output;
            private: ::Windows::UI::Xaml::Controls::ListBox^ Playlist;
            private: ::Windows::UI::Xaml::Controls::Image^ ImageSource;
            private: ::Windows::UI::Xaml::Controls::ListBoxItem^ Item1;
            private: ::Windows::UI::Xaml::Controls::ListBoxItem^ Item2;
            private: ::Windows::UI::Xaml::Controls::ListBoxItem^ Item3;
            private: ::Windows::UI::Xaml::Controls::ListBoxItem^ Item4;
            private: ::Windows::UI::Xaml::Controls::ListBoxItem^ Item5;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ InputTextBlock1;
            private: ::Windows::UI::Xaml::Controls::Button^ playSlideshow;
            private: ::Windows::UI::Xaml::Controls::Button^ pauseSlideshow;
            private: ::Windows::UI::Xaml::Controls::Button^ previousItem;
            private: ::Windows::UI::Xaml::Controls::Button^ nextItem;
            private: ::Windows::UI::Xaml::VisualState^ DefaultLayout;
            private: ::Windows::UI::Xaml::VisualState^ Below768Layout;
        };
    }
}

